# Generated by Django 5.2 on 2025-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price_enrollment_date_enrolled_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/'),
        ),
    ]
